[window]
decorations = "none"
padding = { x = 18, y = 14 }
opacity = 0.55

[font]
size = 11.0

[colors]

[colors.primary]
background = "#121212"
foreground = "#E5E5E5"

[colors.cursor]
text = "#121212"
cursor = "#E5E5E5"

[colors.normal]
black   = "#1e1e2e"
red     = "#F38BA8"
green   = "#A6E3A1"
yellow  = "#F9E2AF"
blue    = "#89B4FA"
magenta = "#CBA6F7"
cyan    = "#94E2D5"
white   = "#E5E5E5"

[colors.bright]
black   = "#585b70"
red     = "#F38BA8"
green   = "#A6E3A1"
yellow  = "#F9E2AF"
blue    = "#89B4FA"
magenta = "#CBA6F7"
cyan    = "#94E2D5"
white   = "#A6ADC8"

[colors.selection]
text = "#121212"
background = "#E5E5E5"

[colors.vi_mode_cursor]
text   = "#121212"
cursor = "#E5E5E5"
